### ISSUE TITLE
Library issues

### ISSUE THREAD

**Issue by PrAsAnNaRePo** [microsoft/torchscale#10]
`cannot import name 'UnencryptedCookieSessionFactoryConfig' from 'pyramid.session' (unknown location)`
I can't install the package either in windows or in Linux systems.

**Comment by shumingma** [comment]
This seems to be a problem on the environment/dependency of torchscale. Could you please try installing apex (see https://github.com/NVIDIA/apex#linux) before installing torchscale?

**Comment by shumingma** [comment]
Close for now. Please feel free to reopen it if it doesn't work by reinstalling apex.
