### ISSUE TITLE
Installer bug - wrong `apex` package installed

### ISSUE THREAD

**Issue by jph00** [microsoft/torchscale#18]
If you `pip install torchscale` then via requirements it also installs `apex` from pypi. However, `apex` on pypi is not Nvidia's apex, but is an unrelated project with many deps. As a result, many other additional deps are also pulled into the installation.

Nvidia's apex is currently not pip-installable, and therefore it should not be listed as a requirement.
cc @shumingma

**Comment by shumingma** [comment]
Thanks for catching that! I've uploaded a fix to ```torchscale==0.1.2``` by removing ```apex``` from the installation dependency and making it an optional package.

**Comment by jph00** [comment]
Many thanks. Closing this.
