### ISSUE TITLE
does torchscale functionalities can impove  modeling generality and capability in case of Session-Based Recommendation system 

### ISSUE THREAD

**Issue by deep-matter** [microsoft/torchscale#2]
i am currently working Session-Based Recommendation system problem, indeed this topic in NLP so quite under progress of improvement, and most of technics used to tackle that problem are Matrix Factorization or GNN recently invidia realized a library TransfomerSRC4, 
i would like to ask if there's a way to use TorchScale functionalities to address the problem Session-Based Recommendation or not yet

**Comment by shumingma** [comment]
Actually, I am not familiar with recommendation models. If Transformers4Rec adopts the standard Transformer architecture as its backbone, I think it's possible to replace the backbone with TorchScale to enjoy the functionalities we have.
