### ISSUE TITLE
Fairseq version compatible with torchscale

### ISSUE THREAD

**Issue by sjelassi** [microsoft/torchscale#25]
Hi, 

Thank you for your great work to develop Torchscale. 

I have been trying to use your codebase but it seems like some modules such as "fairseq.models.squad" that were available during the development of Torchscale are not available anymore in the current version of Fairseq. 

Can you let me know the version (or the commit) of fairseq you are using to make Torchscale work? 

Thanks for your help,
Samy

**Comment by shumingma** [comment]
This version of fairseq can be found at https://github.com/microsoft/torchscale/tree/main/examples/fairseq#setup

Or directly refer to https://github.com/shumingma/fairseq/tree/moe
