### ISSUE TITLE
Can't pickle

### ISSUE THREAD

**Issue by kashif** [microsoft/torchscale#3]
Hello! I'm running into the following pickling errors and thus Pytorch lightning is unable to checkpoint the model I believe:

```py
import pickle

from torchscale.architecture.encoder import Encoder
from torchscale.architecture.config import EncoderConfig

enc = EncoderConfig()
pickle.dumps(Encoder(enc))

AttributeError: Can't pickle local object 'get_activation_fn.<locals>.<lambda>'
```

Which is coming from https://github.com/microsoft/torchscale/blob/main/torchscale/component/feedforward_network.py#L88

**Comment by shumingma** [comment]
Fixed by PR #4 
Thanks for the contribution!
