### ISSUE TITLE
EncoderDecoder Configuration Issue

### ISSUE THREAD

**Issue by klae01** [microsoft/torchscale#32]
I've identified a problem in the `EncoderDecoderConfig` class within the `architecture` module of the `torchscale` package. 

The `EncoderDecoderConfig` class currently does not contain the `normalize_output` element. This missing element is causing some functionality of the package to not work as expected. Specifically, when the `EncoderDecoder` class is used with a `EncoderDecoderConfig` object, the lack of the `normalize_output` element can lead to incorrect behavior.

I recommend adding the `normalize_output` element to the `EncoderDecoderConfig` class. I believe that this change will resolve the issue and make the `EncoderDecoder` class function as expected.

Furthermore, I have added a new GitHub Action in pull request #31  to help prevent issues like this in the future.

**Comment by shumingma** [comment]
Thank you for the contribution! Already fixed the config issue and merged the PR.
