### ISSUE TITLE
Longnet Code Release

### ISSUE THREAD

**Issue by arnavdantuluri** [microsoft/torchscale#37]
Hello all, just wondering whether there is an ETA on the official release of the long net code, it was mentioned here https://github.com/microsoft/unilm/issues/1182#issuecomment-1624938095 that the long net code would be released as part of torchscale. Looking forward to the seeing the official implementation!

**Comment by JacksonZ03** [comment]
I sent an email to one of the researchers. Hopefully, I get a reply. This paper is honestly a giant step forward

**Comment by arnavdantuluri** [comment]
Please let us know if you get a reply 🙂

**Comment by LiutongZhou** [comment]
Looking forward to it

**Comment by pokameng** [comment]
looking forward to the code releasing!!!

**Comment by AlexanderChen1989** [comment]
please release the code!

**Comment by CanyonWind** [comment]
Would appreciate it a lot if it's possible to give the community a heads-up when the ETA would be

**Comment by fkodom** [comment]
For anyone that's interested, I built an (unofficial) LongNet implementation here:
https://github.com/fkodom/dilated-attention-pytorch

There are no pretrained weights -- I don't have the personal compute budget for that. 😂 But the main concepts are there, and I reproduced scaled-down versions of the inference benchmarks.

Hopefully it's interesting for tinkering and exploration, at least until the official code comes out. 😉

**Comment by MHarris021** [comment]
Any updates on when this might officially come out? @fkodom 's  repo https://github.com/fkodom/dilated-attention-pytorch is a pretty good implementation while we wait. @DeepDream2045 and I were able to benchmark it processing 64 Million tokens on an RTX A5000 in Linear time. It scaled up nicely to handle 256 Million tokens on a single A100 as well. This was with 32 embed_dim and 4 num_heads. We were also able to validate that the MultiheadDilated Attention  Class could  handle 32 Million tokens with an embed_dim 128 and num_heads 8 on an A100. Comparable numbers on an RTX A5000 were 1 Million tokens w/ an embed_dim 1024 and 16 num_heads.

**Comment by MHarris021** [comment]
![tokens-32M-embed_dim-128-heads-8](https://github.com/microsoft/torchscale/assets/2326675/25baf173-95da-4fb7-99dd-223e7092c959)

**Comment by agemagician** [comment]
@shumingma @gitnlp @sunyt32 @donglixp @buaahsh @microsoftopensource 

Any update regarding release date for the code ? 

I am currently working in a project with Google and I am interested to benchmark your new architecture.

**Comment by agemagician** [comment]
Your response is highly appreciated @shumingma @gitnlp @sunyt32 @donglixp @buaahsh @microsoftopensource

**Comment by agemagician** [comment]
Thanks @donglixp for assinging @shumingma for the model release.

@shumingma any estimation when the model code will be released ?

**Comment by agemagician** [comment]
@shumingma and @donglixp  it would be great if you could share the timeline for all of us.

**Comment by shumingma** [comment]
Hi all, we have finally released the code of [LongNet](https://github.com/microsoft/torchscale/blob/main/torchscale/model/LongNet.py) (together with [LongViT](https://github.com/microsoft/torchscale/tree/main/examples/longvit)). Thank you for your patience. Have fun!
