### ISSUE TITLE
can not download dict.txt

### ISSUE THREAD

**Issue by robotzheng** [microsoft/torchscale#41]
when link https://publicmodel.blob.core.windows.net/torchscale/vocab/dict.txt

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>PublicAccessNotPermitted</Code>
<Message>Public access is not permitted on this storage account. RequestId:6a16dad1-301e-000f-6855-c0dbf7000000 Time:2023-07-27T06:39:12.1140517Z</Message>
</Error>

**Comment by shumingma** [comment]
Yes, the server is down. I've attached the dictionary file below.

[dict.txt](https://github.com/microsoft/torchscale/files/12183441/dict.txt)

**Comment by robotzheng** [comment]
Thanks
