### ISSUE TITLE
the meaning of "incremental_state" in RetNet

### ISSUE THREAD

**Issue by jhl-Det** [microsoft/torchscale#42]
Hi there~,
Thanks for your great work RetNet. i have encountered a problem when I try to define "incremental_state".
Could you provide me some usage about it or explain more?
Thanks,
Best regards.

**Comment by Anker-ZX-AI** [comment]
I think it's kind of like the hidden_state in RNN, stores previous step k*v and scale, so it defines in a dict, for the initial state I just use an empty dict: `incremental_state = {}`

**Comment by shumingma** [comment]
Yes, @Anker-ZX-AI is right. It's to store the KV caches.

**Comment by jhl-Det** [comment]
THANK YOU！
