### ISSUE TITLE
AttributeError: 'EncoderConfig' object has no attribute 'decoder_layers'

### ISSUE THREAD

**Issue by dedekinds** [microsoft/torchscale#43]
<img width="941" alt="图片" src="https://github.com/microsoft/torchscale/assets/26075974/7a910565-5e85-434f-ae23-83b8285478ca">

 .

.

Hi, I plan to reproduce the results of the WMT-17 translation task as presented in the deepnet paper. Could you please let me know what the command for running the script should be? For example, what should `--arch` be set to? According to the examples provided in the readme, should I run the following command?
```
cd examples/fairseq/
python -m torch.distributed.launch --nproc_per_node=2 --nnodes=1 train.py \
    ${PATH_TO_DATA} \
    --arch mt_base --share-decoder-input-output-embed \
    --optimizer adam --adam-betas '(0.9, 0.98)' --clip-norm 0.0 \
    --lr 5e-4 --lr-scheduler inverse_sqrt --warmup-updates 4000 \
    --dropout 0.3 --weight-decay 0.0001 \
    --max-tokens 4096 --fp16  --deepnorm
```

However, when I add `--deepnorm` to the command from example, it throws an error: AttributeError: 'EncoderConfig' object has no attribute 'decoder_layers'. Could you please advise on the correct command and settings to obtain results similar to Table 1 in the paper? Thank you!

<img width="826" alt="图片" src="https://github.com/microsoft/torchscale/assets/26075974/7dd41467-92dd-489e-9e64-8181648e1748">

**Comment by shumingma** [comment]
This has been fixed by the commit. https://github.com/microsoft/torchscale/commit/5356b252c43b2cba3638b0646c4f861854a4a854

Please have a try on the latest commit.

**Comment by dedekinds** [comment]
> This has been fixed by the commit. [5356b25](https://github.com/microsoft/torchscale/commit/5356b252c43b2cba3638b0646c4f861854a4a854)
> 
> Please have a try on the latest commit.

It works, thank you!
