### ISSUE TITLE
Multi-Scale Retention:  Why include position embeddings explicitly?

### ISSUE THREAD

**Issue by fkodom** [microsoft/torchscale#48]
My question is about the [RetNet paper](https://arxiv.org/pdf/2307.08621v3.pdf), which leads to the implementation here...

Why include the positional embedding updates directly in the multi-scale retention layer, rather than just applying them to the RetNet inputs?

![Screen Shot 2023-08-02 at 9 35 48 AM](https://github.com/microsoft/torchscale/assets/45951340/0f36902f-6e1d-4a87-b825-5861039612f0)

![Screen Shot 2023-08-02 at 9 29 37 AM](https://github.com/microsoft/torchscale/assets/45951340/f1dcc8d2-3ed4-475f-aa96-7e51b49e1410)

IMO, this seems overly specific to the language modeling use case.  Other applications of retention/attention should be free to use whatever positional embeddings they need/want.

The retention formulation is still self-consistent (i.e. equivalent for parallel, recurrent, chunkwise) without explicitly including positional embeddings in the retention layer.  See Equations (1) and (2):

![Screen Shot 2023-08-02 at 9 41 15 AM](https://github.com/microsoft/torchscale/assets/45951340/39c15d90-9b81-4d9f-9016-413798c0349f)

Instead of forcing positional embeddings into the retention formulation, we can just set `A` equal to the decay matrix `D`.  The parallel/recurrent/chunkwise formulations are still equivalent, and we remove the hard-coded dependence on xPos embeddings in the retention layer.

Conceptually, I'm thinking of how to apply RetNet to other data domains (images, heterogeneous graphs, etc).  In those cases, the xPos embeddings are not reflective of the **actual** position in the sequence (2D position in image, generic position within a graph, etc).  Does it make sense to remove the explicit position embedding from the retention layer, or am I missing something?

**Comment by sunyt32** [comment]
$e^{i\theta}$ works well on language modeling, and we set it as default. For other domains, we don't evaluate on them yet, and I agree that rotation may not be the best option. Also, maybe an optimization technique is needed, but setting them as learnable parameters naively will cause nan in gradients. You can try to adjust it manually or explore a usable method to optimize it.

**Comment by donglixp** [comment]
It depends on how you understand "position embeddings". For example, we can also add the position embeddings (such as "generic position within a graph") to the token embeddings, where the positions are regarded as attributes.

**Comment by fkodom** [comment]
Thanks!  This is exactly what I was looking for. 😎
