### ISSUE TITLE
Retnet training is slow

### ISSUE THREAD

**Issue by Zth9730** [microsoft/torchscale#55]
Hi, when I use retnet's parallel  mode to train, it's very slow, I observe the gou memory usage, it's very small, what's going on?
Thank you!
```[tasklist]
### Tasks
```

**Comment by sunyt32** [comment]
Can you show your script for reproduction? It sounds weird because of the low memory usage. You can compare the RetNet training with the transformer module in TorchScale.

**Comment by Zth9730** [comment]
> 

Thanks a lot， I checked my config and find my batchsize is small, sry!
