### ISSUE TITLE
Question about is_first_step and Retnet

### ISSUE THREAD

**Issue by tdomhan** [microsoft/torchscale#58]
In the code when `is_first_step` is `True` then activate_recurrent is set to `False` here: 
https://github.com/microsoft/torchscale/blob/main/torchscale/architecture/retnet.py#L362 

I was wondering what the reason for this is?
Should one us `is_first_step=False` when using the recurrent mode of Retnet?

**Comment by shumingma** [comment]
At the first step, the input (e.g., a prompt) may contain multiple tokens, while the recurrent mode only accepts one token at a time.

**Comment by tdomhan** [comment]
ohh, understood! So it's for prompt. Thanks!
