### ISSUE TITLE
requires dict.txt and sentencepiece.bpe.model

### ISSUE THREAD

**Issue by lpyhdzx** [microsoft/torchscale#6]
Could you provide "dict.txt" and "sentencepiece.bpe.model" (i.e., files in doc ''Example: BERT Pretraining'') for further exploring pretraining BERT with deepnorm.

**Comment by shumingma** [comment]
Here you are: 

[dict.txt](https://publicmodel.blob.core.windows.net/torchscale/vocab/dict.txt) 
[sentencepiece.bpe.model](https://publicmodel.blob.core.windows.net/torchscale/vocab/sentencepiece.bpe.model)

Please note that they are English only.

**Comment by robotzheng** [comment]
can not download
