### ISSUE TITLE
Could you please explain the reason behind defining TEMPERATURE_FOR_L_UAX in the code without actually using it?

### ISSUE THREAD

**Issue by Ruiyuan-Zhang** [microsoft/torchscale#63]
As the title says, there was only one result.

<img width="1101" alt="image" src="https://github.com/microsoft/torchscale/assets/71813586/1669ffa0-b37a-4e71-a629-57d2b2d936c9">

**Comment by donglixp** [comment]
https://github.com/xy980523/MoEc_model/blob/45c83c8c483eb278d334feded844e0d3d5d96e27/unilm/modules/tmoe/top1gate.py#L86
