### ISSUE TITLE
There're a confusion in torchscale

### ISSUE THREAD

**Issue by lovekang3344** [microsoft/torchscale#65]
When using `from torchscale.architecture.config import RetNetConfig` , I got a error.
```python
      from torchscale.architecture.config import RetNetConfig
ImportError: cannot import name 'RetNetConfig' from 'torchscale.architecture.config'

```

But I can import Decoder and  EncoderDecoder. help!

**Comment by lovekang3344** [comment]
I got it. When I use `pip install torchscale`，I realized that there isn't a class here called RetNetConfig in config.py. When I pulled the code directly from GitHub and replaced the original one with the torchscale folder in it, it solved the issue.

**Comment by donglixp** [comment]
Thanks for reporting the issue. We will fix it.

**Comment by shumingma** [comment]
The latest release (https://pypi.org/project/torchscale/) should fix this problem. Please try upgrading torchscale. Any problem feel free to reopen the issue. Thanks!
