### ISSUE TITLE
pip package does not contain RetNet

### ISSUE THREAD

**Issue by fabienGenhealth** [microsoft/torchscale#67]
The latest release 0.2.0 is from March (see https://pypi.org/project/torchscale/#history), predating the introduction of RetNet in this repo. As such the README is misleading since it is not possible to create a RetNet model with a pip install.
When is the next release planned?

**Comment by donglixp** [comment]
Thanks for reporting the issue. We will fix it.

**Comment by shumingma** [comment]
We have released 0.3.0 (https://pypi.org/project/torchscale/). The problem is supposed to be fixed. Please try. Thanks!
