### ISSUE TITLE
Question about RetNetRelPos

### ISSUE THREAD

**Issue by hyunwoongko** [microsoft/torchscale#80]
In the retnet code,
https://github.com/microsoft/torchscale/blob/main/torchscale/architecture/retnet.py#L25
this creates `inv_freq` (`angle` in this code) using `torch.linspace(0, 1, dim/2)`.

but generally people creates it using `torch.arange(0, dim, 2) / dim` like the following:
https://github.com/huggingface/transformers/blob/main/src/transformers/models/llama/modeling_llama.py#L120

Why authors implemented inv_freq like that? Is there any special reason?

**Comment by sunyt32** [comment]
They are almost the same. It's not a big deal.

**Comment by hyunwoongko** [comment]
Thanks!
